- name: Install Docker

  hosts:
    - common_programs
    
  gather_facts: true
  
  vars_files:
    - variables/provision.yml

  vars:
     ansible_python_interpreter: "{{ aws.instance.venv.dir.path }}/bin/python"
     PYTHON_VERSION: "{{ aws.instance.python.version }}"
     DOCKER_VERSION: "{{ aws.instance.docker.version }}"
  pre_tasks:
           
    - name: Python version
      ansible.builtin.shell: '{{ aws.instance.python.install.dir.path }}/{{ aws.instance.python.executable }} -V'
      register: python_ver
      ignore_errors: true
                 
    - assert:
        that:
          - PYTHON_VERSION in python_ver.stdout   
          
    - name: Fetch Docker version
      shell: docker -v | cut -b 16-19
      register: docker_version
          
    - name: End the play if Docker is installed
      ansible.builtin.meta: end_play
      when:
        - (docker_version.stdout | int > 0) and (docker_version.stdout is version_compare(DOCKER_VERSION, '>='))  
                  
    - name: Configuration variables
      ansible.builtin.debug:
        msg:
          - 'SSH instance port: {{ ansible_port }}'
          - 'SSH instance user: {{ ansible_user }}'
          - 'SSH instance key: {{ ansible_private_key_file }}'
          - 'Python version: {{ PYTHON_VERSION }}'
          - 'Docker version: {{ docker_version.stdout }}'
                                                          
  tasks:

    - name: Install Docker
      become: true
      yum:
        name: "docker"
        state: present

    - name: Enable Docker service
      become: true
      service:
        name: docker
        state: started
        enabled: true

    - name: Install docker-compose
      become: true
      get_url:
        url: "{{aws.instance.docker.compose.download.url}}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Create group Docker
      ansible.builtin.group:
        name: docker
        state: present
        
    - name: Adding user "{{ ansible_user }}" to group docker
      become: true
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: true        

    - name: Restart Docker
      become: true
      service:
        name: docker
        state: restarted 
      