- name: Install Tomcat 10

  hosts:
    - database_mariadb
    
  gather_facts: false
  
  vars_files:
    - variables/provision.yml
    - variables/secrets.yml

#  vars:
#     JAVA_HOME: "{{ aws.instance.programs.install.dir.path }}/{{ aws.instance.java.root.dir.name }}"  
#     CATALINA_HOME: "{{ aws.instance.programs.install.dir.path }}/{{ aws.instance.tomcat.root.dir.name }}"
#     HTTPS_PORT: "{{ aws.instance.tomcat.https.port }}"
    
  pre_tasks:
       
    - name: Controller host configuration
      ansible.builtin.debug:
        msg:
          - 'SSH instance port: {{ ansible_port }}'
          - 'SSH instance user: {{ ansible_user }}'
          - 'SSH instance key: {{ ansible_private_key_file }}'
          - 'MariaDB version: {{ aws.instance.mariadb.version }}'

    - name: Fetch MariaDB	 version
      shell: mariadb --version 2>&1 | awk '{print $3}' | sed 's/"//g'
      register: mariadb_version
      
    - name: Debug md version
      ansible.builtin.debug:
        msg:
          - 'mariadb_version: {{ mariadb_version }}'      
        
    - name: End the play if MariaDB is installed
      ansible.builtin.meta: end_play
      when:
        - mariadb_version.stdout | length > 0 and mariadb_version.stdout is version_compare(aws.instance.mariadb.version, '>=')     
      ignore_errors: true
                                                
  tasks:
      
    - name: Add Amazon linux extras MariaDB repository
      become: true
      ansible.builtin.command: 'amazon-linux-extras enable mariadb{{ aws.instance.mariadb.version }}'

    - name: Clean yum metadata
      become: true
      ansible.builtin.command: 'yum clean metadata'  

    - name: Install MariaDB
      become: true
      ansible.builtin.command: 'yum install -y mariadb'       
      
    - name: Start MariaDB server
      become: true
      become_method: sudo     
      ansible.builtin.systemd_service:
        state: restarted
        enabled: true
        name: mariadb        
                 
  post_tasks:
  
 
                
                      
