- name: Installs common programs
  hosts:
    - all
  gather_facts: false
  
  vars_files:
    - variables/vars.yml
    - variables/provision.yml
    - "{{ lookup('ansible.builtin.env', 'PROJECT_DIR') }}/config/datacenter.json"
    
  pre_tasks:
  
    - name: 'variables test'
      ansible.builtin.debug:
        msg: 
        - "xxx: {{ Datacenter.Description }}"
      
  tasks:
    - name: update yum cache
      ansible.builtin.yum: update_cache=true
  
    - name: upgrade all packages
      ansible.builtin.yum: name=* state=latest 
                         
    - name: Install a list of packages 
      ansible.builtin.yum:
        name:
          - supervisor
          - git
          - vim         
        state: present
        